server:
  port: 8159
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: opendoc-blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asd?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: 账号
    password: 密码
#MyBatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #type-enums-package: com.git.sys.model.enums.BaseEnum
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.git.model
  global-config:
    db-config:
      id-type: auto #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      insertStrategy: not_null #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true #驼峰下划线转换
    cache-enabled: false
    #不加这个查询数据为空时，字段将被隐藏
    default-statement-timeout: 5000
